# Generated by Django 4.1.3 on 2023-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他')], max_length=3, null=True),
        ),
    ]
