# Generated by Django 4.1.4 on 2023-01-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='Acici Name', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_msg',
            field=models.CharField(blank=True, default='一言メッセージ', max_length=32, null=True),
        ),
    ]
