# Generated by Django 4.1.3 on 2023-01-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_nickname_alter_profile_short_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgaes', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_user', to='accounts.profile')),
                ('tgt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='accounts.profile')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
