# Generated by Django 4.1.3 on 2023-01-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comparisonimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonimage',
            old_name='imgaes',
            new_name='images',
        ),
    ]
