# Generated by Django 4.1.4 on 2023-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_imgaes_comparisonimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonimage',
            name='ret',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
