# Generated by Django 4.1.4 on 2023-01-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('followed', models.ManyToManyField(blank=True, related_name='followed_by', to='friend.friend')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='accounts.profile')),
            ],
        ),
    ]
