# Generated by Django 4.1.4 on 2023-01-17 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0002_alter_friend_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followed',
        ),
        migrations.AddField(
            model_name='friend',
            name='followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
