# Generated by Django 4.1.4 on 2023-01-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_remove_message_user_message_receiver_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to='friend.friend'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to='friend.friend'),
        ),
    ]
