# Generated by Django 4.1.4 on 2023-01-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0008_room_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_name',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
