# Generated by Django 4.1.4 on 2023-01-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
