# Generated by Django 4.1.4 on 2023-01-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0015_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
