# Generated by Django 4.1.3 on 2023-01-12 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('main_categ', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_categ', models.CharField(blank=True, max_length=255, null=True)),
                ('contents_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('q_title', models.CharField(blank=True, max_length=255, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
                ('q4', models.CharField(blank=True, max_length=255, null=True)),
                ('q5', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('a1', models.IntegerField(blank=True, null=True)),
                ('a2', models.IntegerField(blank=True, null=True)),
                ('a3', models.IntegerField(blank=True, null=True)),
                ('a4', models.IntegerField(blank=True, null=True)),
                ('a5', models.IntegerField(blank=True, null=True)),
                ('a_val', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_a.contents')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_a.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
